# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appesi', '0008_remove_computadoramod_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesoriomod',
            name='imagen',
        ),
    ]
