# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appesi', '0009_remove_accesoriomod_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesoriomod',
            old_name='tipoaccesoriof',
            new_name='tipoaccesoriosf',
        ),
    ]
